services:
  - type: web
    name: worst-chess-bot
    env: python
    buildCommand: pip install -r Code/requirements.txt
    startCommand: gunicorn Code.app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production 